site_name: SOP de ventas Lícita consultores

theme:
  name: material
  palette:
    - scheme: default
      primary: lime         # Verde lima (navbar, encabezados, links)
      accent: light green   # Verde claro para acentos (botones, resaltados)
    - scheme: slate
      primary: lime
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - Introducción: intro.md
  - GHL como herramienta de ventas:
      - Uso del Sistema: GHL/ghlventas.md
      - Configuración de Calendarios y agendamiento: GHL/ghlotros.md
  - Appointment Setting:
      - Embudo de ventas parte 1 (Setting): Appointment/appointmentcontent.md
      - Favoritos: Appointment/favoritos.md
  - Seguimientos:
      - Procedimiento Estandar: Seguimientos/procedimientoseg.md
      - Otros: Seguimientos/seguimientosotros.md
  - Cierre de ventas:
      - Procedimiento Estandar: Cierreventas/cierreprocedimiento.md
      - Otros: Cierreventas/ventasotros.md
