site_name: SOP de ventas Lícita consultores

theme:
  name: material
  palette:
    - scheme: default
      primary: lime         
      accent: light green  
    - scheme: slate
      primary: lime
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - Introducción: intro.md
  - GHL como herramienta de ventas:
      - Uso del Sistema:
          - Conversaciones y sus funciones: GHL/conversaciones.md
          - Movimiento en el CRM: GHL/movcrm.md
          - Configuración de Calendarios y agendamiento: GHL/ghlotros.md
          - Reporte Diario de Ventas: GHL/reporteVentas.md
  - Appointment Setting:
      - Embudo de ventas parte 1 (Setting): Appointment/appointmentcontent.md
      - Estrategia de prospección: Appointment/estrategias.md
      - Triaje: Appointment/triaje.md
  - Seguimientos:
      - Procedimiento Estandar: Seguimientos/procedimientoseg.md
      - Otros: Seguimientos/seguimientosotros.md
  - Cierre de ventas:
      - Procedimiento Estandar: Cierreventas/cierreprocedimiento.md
      - Formulario de un cliente nuevo: Cierreventas/ventasotros.md
  - Presentacion Licita: Presentacion.md
